#include <iostream>
#include <fstream>
#include <chrono>
#include <ctime>
#include <string>
#include <iomanip>
#include "CPUInfo.h"
#include "MemoryInfo.h"
#include "DiskInfo.h"
#include "OSInfo.h"
#include "UptimeInfo.h"
#include "GPUInfo.h"

using namespace std;

// No idea what this does. Generated by ChatGPT lol
string getCurrentDateTime() {
    auto now = chrono::system_clock::now();
    time_t currentTime = chrono::system_clock::to_time_t(now);
    tm *ltm = localtime(&currentTime);
    stringstream ss;
    ss << 1900 + ltm->tm_year << "-" 
       << setfill('0') << setw(2) << 1 + ltm->tm_mon << "-"
       << setfill('0') << setw(2) << ltm->tm_mday << "-"
       << setfill('0') << setw(2) << ltm->tm_hour << "-"
       << setfill('0') << setw(2) << ltm->tm_min << "-"
       << setfill('0') << setw(2) << ltm->tm_sec;
    return ss.str();
}

void writeLog(const string& logContent) {
    ofstream logFile("SysInfo-" + getCurrentDateTime() + ".log");
    logFile << logContent;
    logFile.close();
}

int main() {
    stringstream output;

    // Collecting system information
    output << "System Information\n";
    output << "====================\n\n";
    
    output << "CPU Information:\n";
    output << getCPUInfo() << "\n\n";

    output << "Memory Information:\n";
    output << getMemoryInfo() << "\n\n";
    
    output << "Disk Space Information:\n";
    output << getDiskInfo() << "\n\n";
    
    output << "Operating System Information:\n";
    output << getOSInfo() << "\n\n";
    
    output << "Uptime:\n";
    output << getUptimeInfo() << "\n\n";
    
    output << "GPU Information:\n";
    output << getGPUInfo() << "\n\n";
    
    // Display the information
    cout << output.str();

    // Save the information to a log file
    writeLog(output.str());

    return 0;
}